const playersData = [
  {
    id: 1,
    name: "Lionel Messi",
    position: "FW-MF",
    age: 35,
    birthDate: "June 24, 1987",
    birthPlace: "Rosario, Argentina",
    height: "170cm",
    weight: "72kg",
    footed: "Left",
    nationalTeam: "Argentina",
    Club: "Paris Saint-Germain",
    img: "Lionel Messi.jpg",
  },
  {
    id: 2,
    name: "Cristiano Ronaldo",
    position: "FW-MF",
    age: 37,
    birthDate: "February 5, 1985",
    birthPlace: "Funchal, Portugal",
    height: "187cm",
    weight: "83kg ",
    footed: "Right",
    nationalTeam: " Portugal",
    Club: "Al Nasr (KSA)",
    img: "Cristiano Ronaldo.jpg",
  },
  {
    id: 3,
    name: "Ansu Fati",
    position: "FW",
    age: 20,
    birthDate: "October 31, 2002",
    birthPlace: "Bissau, Guinea-Bissau",
    height: "178cm",
    weight: "68kg",
    footed: "Right",
    nationalTeam: "Spain",
    Club: "Barcelona",
    img: "Ansu Fati.jpg",
  },
  {
    id: 4,
    name: "Bernardo Silva",
    position: "FW-MF",
    age: 28,
    birthDate: "August 10, 1994",
    birthPlace: "Lisbon, Portugal",
    height: "173cm",
    weight: "64kg",
    footed: "Left",
    nationalTeam: "Portugal",
    Club: "Manchester City",
    img: "Bernardo Silva.jpg",
  },
  {
    id: 5,
    name: "Angel Di Maria",
    position: "FW-MF",
    age: 34,
    birthDate: "February 14, 1988",
    birthPlace: "Rosario, Argentina",
    height: "180cm",
    weight: "69kg ",
    footed: "Left",
    nationalTeam: "Argentina",
    Club: "Juventus",
    img: "Angel Di Maria.jpg",
  },
  {
    id: 6,
    name: "Andreas Christensen",
    position: "DF (CB)",
    age: 26,
    birthDate: "April 10, 1996",
    birthPlace: "Lillerød, Denmark",
    height: "188cm",
    weight: "73kg",
    footed: "Right",
    nationalTeam: "Denmark",
    Club: "Barcelona",
    img: "Andreas Christensen.jpg",
  },
  {
    id: 7,
    name: "Antonio Rudiger",
    position: "DF",
    footed: "Right",
    height: "191cm",
    weight: "84kg",
    birthDate: "March 3, 1993",
    age: 29,
    birthPlace: "Berlin, Germany",
    nationalTeam: "Germany",
    Club: "Real Madrid",
    img: "Antonio Rudiger.jpg",
  },
  {
    id: 8,
    name: "Andrew Robertson",
    position: "DF-MF",
    footed: "Left",
    height: "178cm",
    weight: "63kg ",
    birthDate: "March 11, 1994",
    age: 28,
    birthPlace: "Glasgow, Scotland",
    nationalTeam: "Scotland",
    Club: "Liverpool",
    img: "Andrew Robertson.jpg",
  },
  {
    id: 9,
    name: "Antony Matheus",
    position: "FW-MF",
    footed: "Left",
    height: "172cm",
    weight: "64kg",
    birthDate: "February 24, 2000",
    age: 22,
    birthPlace: "São Paulo, Brazil",
    nationalTeam: "Brazil",
    Club: "Manchester United",
    img: "Antony Matheus.jpg",
  },
  {
    id: 10,
    name: "Aurelien Tchouameni",
    position: "MF",
    footed: "Right",
    height: "185cm",
    weight: "74kg ",
    birthDate: "January 27, 2000",
    age: 22,
    birthPlace: "Rouen, France",
    nationalTeam: "France",
    Club: "Real Madrid",
    img: "Aurelien Tchouameni.jpg",
  },
  {
    id: 11,
    name: "Aymeric Laporte",
    position: "DF ",
    footed: "Left",
    height: "189cm",
    weight: "84kg",
    birthDate: "May 27, 1994",
    age: 28,
    birthPlace: "Agen, France",
    nationalTeam: "France",
    Club: "Manchester City",
    img: "Aymeric Laporte.jpg",
  },
  {
    id: 12,
    name: "Bruno Fernandes",
    position: "FW-MF",
    footed: "Right",
    height: "173cm",
    weight: "64kg ",
    birthDate: "September 8, 1994",
    age: 28,
    birthPlace: "Maia, Portugal",
    nationalTeam: "Portugal",
    Club: "Manchester United",
    img: "Bruno Fernandes.jpg",
  },
  {
    id: 13,
    name: "Bukayo Saka",
    position: "FW-MF",
    footed: "Left",
    height: "178cm",
    weight: "64kg",
    birthDate: "September 5, 2001",
    age: 21,
    birthPlace: "Ealing, England",
    nationalTeam: "England",
    Club: "Arsenal",
    img: "Bukayo Saka.jpg",
  },
  {
    id: 14,
    name: "Carlos Casemiro",
    position: "MF",
    footed: "Right",
    height: "184cm",
    weight: "79kg",
    birthDate: "February 23, 1992",
    age: 30,
    birthPlace: "São José dos Campos, Brazil",
    nationalTeam: "Brazil",
    Club: "Manchester United",
    img: "Carlos Casemiro.jpg",
  },
  {
    id: 15,
    name: "Christian Pulisic",
    position: "FW-MF",
    footed: "Right",
    height: "172cm",
    weight: "68kg",
    birthDate: "September 18, 1998",
    age: 24,
    birthPlace: "Pennsylvania, United States",
    nationalTeam: "USA",
    Club: "Chelsea",
    img: "Christian Pulisic.jpg",
  },
  {
    id: 16,
    name: "Darwin Nunez",
    position: "FW",
    footed: "Right",
    height: "187cm",
    weight: "79kg",
    birthDate: "June 24, 1999",
    age: 23,
    birthPlace: "Artigas, Uruguay",
    nationalTeam: "Uruguay",
    Club: "Liverpool",
    img: "Darwin Nunez.jpg",
  },
  {
    id: 17,
    name: "David Alaba",
    position: "DF-MF",
    footed: "Left",
    height: "180cm",
    weight: "72kg ",
    birthDate: "June 24, 1992",
    age: 30,
    birthPlace: "Austria",
    nationalTeam: "Austria",
    Club: "Real Madrid",
    img: "David Alaba.jpg",
  },
  {
    id: 18,
    name: "David De Gea",
    position: "GK",
    footed: "Right",
    height: "192cm",
    weight: "76kg",
    birthDate: "November 7, 1990",
    age: 32,
    birthPlace: "Madrid, Spain",
    nationalTeam: "Spain",
    Club: "Manchester United",
    img: "David De Gea.jpg",
  },
  {
    id: 19,
    name: "Dusan Vlahovic",
    position: "FW",
    footed: "Left",
    height: "190cm",
    weight: "83kg ",
    birthDate: "January 28, 2000",
    age: 22,
    birthPlace: "Belgrade, Serbia",
    nationalTeam: "Serbia",
    Club: "Juventus",
    img: "Dusan Vlahovic.jpg",
  },
  {
    id: 20,
    name: "Eden Hazard",
    position: "FW-MF",
    footed: "Right",
    height: "173cm",
    weight: "74kg",
    birthDate: "January 7, 1991",
    age: 32,
    birthPlace: "La Louvière, Belgium",
    nationalTeam: "Belgium",
    Club: "Real Madrid",
    img: "Eden Hazard.jpg",
  },
  {
    id: 21,
    name: "Eder Militao",
    position: "DF-MF",
    footed: "Right",
    height: "186cm",
    weight: "78kg ",
    birthDate: "January 18, 1998",
    age: 24,
    birthPlace: "Sertãozinho, Brazil",
    nationalTeam: "Brazil",
    Club: "Real Madrid",
    img: "Eder Militao.jpg",
  },
  {
    id: 22,
    name: "Ederson Moraes",
    position: "GK ",
    footed: "Left",
    height: "188cm",
    weight: "88kg ",
    birthDate: "August 17, 1993",
    age: 29,
    birthPlace: "Osasco, Brazil",
    nationalTeam: "Brazil",
    Club: "Manchester City",
    img: "Ederson Moraes.jpg",
  },
  {
    id: 23,
    name: "Eduardo Camavinga",
    position: "MF ",
    footed: "Left",
    height: "182cm",
    weight: "68kg ",
    birthDate: "November 10, 2002",
    age: 20,
    birthPlace: "Cabinda, Angola",
    nationalTeam: "France",
    Club: "Real Madrid",
    img: "Eduardo Camavinga.jpg",
  },
  {
    id: 24,
    name: "Eric Garcia",
    position: "DF ",
    footed: "Right",
    height: "183cm",
    weight: "73kg",
    birthDate: "January 9, 2001",
    age: 21,
    birthPlace: "Barcelona, Spain",
    nationalTeam: "Spain",
    Club: "Barcelona",
    img: "Eric Garcia.jpg",
  },
  {
    id: 25,
    name: "Erling Haaland",
    position: "FW ",
    footed: "Left",
    height: "191cm",
    weight: "87kg ",
    birthDate: "July 21, 2000",
    age: 22,
    birthPlace: "Leeds, England",
    nationalTeam: "Norway",
    Club: "Manchester City",
    img: "Erling Haaland.jpg",
  },
  {
    id: 26,
    name: "Fabinho",
    position: "DF-MF",
    footed: "Right",
    height: "188cm",
    weight: "78kg",
    birthDate: "October 23, 1993",
    age: 29,
    birthPlace: "Campinas, Brazil",
    nationalTeam: "Brazil",
    Club: "Liverpool",
    img: "Fabinho.jpg",
  },
  {
    id: 27,
    name: "Federico Valverde",
    position: "FW-MF",
    footed: "Right",
    height: "183cm",
    weight: "72kg",
    birthDate: "July 22, 1998",
    age: 24,
    birthPlace: "Montevideo, Uruguay",
    nationalTeam: "Uruguay",
    Club: "Real Madrid",
    img: "Federico Valverde.jpg",
  },
  {
    id: 28,
    name: "Ronald Araujo",
    position: "DF",
    footed: "Right",
    height: "188cm",
    weight: "78kg",
    birthDate: "March 7, 1999",
    age: 23,
    birthPlace: "Rivera, Uruguay",
    nationalTeam: "Uruguay",
    Club: "Barcelona",
    img: "Ronald Araujo.jpg",
  },
  {
    id: 29,
    name: "Ferran Torres",
    position: "FW-MF",
    footed: "Right",
    height: "184cm",
    weight: "77kg",
    birthDate: "February 29, 2000",
    age: 22,
    birthPlace: "Foios, Spain",
    nationalTeam: "Spain",
    Club: "Barcelona",
    img: "Ferran Torres.jpg",
  },
  {
    id: 30,
    name: "Franck Kessie",
    position: "DF-MF",
    footed: "Right",
    height: "183cm",
    weight: "76kg ",
    birthDate: "December 19, 1996",
    age: 26,
    birthPlace: "Ouragahio, Côte d'Ivoire",
    nationalTeam: "Cote d'Ivoire",
    Club: "Barcelona",
    img: "Franck Kessie.jpg",
  },
  {
    id: 31,
    name: "Frenkie de Jong",
    position: "DF-MF",
    footed: "Right",
    height: "180cm",
    weight: "68kg ",
    birthDate: "May 12, 1997",
    age: 25,
    birthPlace: "Arkel, Netherlands",
    nationalTeam: "Netherlands",
    Club: "Barcelona",
    img: "Frenkie de Jong.jpg",
  },
  {
    id: 32,
    name: "Gabriel Jesus",
    position: "FW-MF",
    footed: "Right",
    height: "177cm",
    weight: "72kg",
    birthDate: "April 3, 1997",
    age: 25,
    birthPlace: "São Paulo, Brazil",
    nationalTeam: "Brazil",
    Club: "Arsenal",
    img: "Gabriel Jesus.jpg",
  },
  {
    id: 33,
    name: "Pablo Gavi",
    position: "MF ",
    footed: "Right",
    height: "173cm",
    weight: "69kg",
    birthDate: "August 5, 2004",
    age: 18,
    birthPlace: "Los Palacios y Villafranca, Spain",
    nationalTeam: "Spain",
    Club: "Barcelona",
    img: "Pablo Gavi.jpg",
  },
  {
    id: 34,
    name: "Gerard Pique",
    position: "DF",
    footed: "Right",
    height: "191cm",
    weight: "84kg ",
    birthDate: "February 2, 1987",
    age: 35,
    birthPlace: "Barcelona, Spain",
    nationalTeam: "Spain",
    Club: "Barcelona",
    img: "Gerard Pique.jpg",
  },
  {
    id: 35,
    name: "Gianluigi Donnarumma",
    position: "GK ",
    footed: "Right",
    height: "196cm",
    weight: "89kg",
    birthDate: "February 25, 1999",
    age: 23,
    birthPlace: "Castellammare di Stabia, Italy",
    nationalTeam: "Italy",
    Club: "Paris Saint-Germain",
    img: "Gianluigi Donnarumma.jpg",
  },
  {
    id: 36,
    name: "Hakim Ziyech",
    position: "FW-MF",
    footed: "Left",
    height: "180cm",
    weight: "69kg",
    birthDate: "March 19, 1993",
    age: 29,
    birthPlace: "Gemeente Dronten, Netherlands",
    nationalTeam: "Morocco",
    Club: "Chelsea",
    img: "Hakim Ziyech.jpg",
  },
  {
    id: 37,
    name: "Harry Kane",
    position: "FW ",
    footed: "Right",
    height: "188cm",
    weight: "73kg",
    birthDate: "July 28, 1993",
    age: 29,
    birthPlace: "Walthamstow, England",
    nationalTeam: "England",
    Club: "Tottenham Hotspur",
    img: "Harry Kane.jpg",
  },
  {
    id: 38,
    name: "Jack Grealish",
    position: "FW-MF",
    footed: "Right",
    height: "175cm",
    weight: "68kg",
    birthDate: "September 10, 1995",
    age: 27,
    birthPlace: "Birmingham, England",
    nationalTeam: "England",
    Club: "Manchester City",
    img: "Jack Grealish.jpg",
  },
  {
    id: 39,
    name: "Jadon Sancho",
    position: "FW-MF",
    footed: "Right",
    height: "180cm",
    weight: "73kg",
    birthDate: "March 25, 2000",
    age: 22,
    birthPlace: "London, England",
    nationalTeam: "England",
    Club: "Manchester United",
    img: "Jadon Sancho.jpg",
  },
  {
    id: 40,
    name: "Jamal Musiala",
    position: "MF",
    footed: "Right",
    height: "184cm",
    weight: "72kg ",
    birthDate: "February 26, 2003",
    age: 19,
    birthPlace: "Stuttgart, Germany",
    nationalTeam: "Germany",
    Club: "Bayern Munich",
    img: "Jamal Musiala.jpg",
  },
  {
    id: 41,
    name: "James Rodriguez",
    position: "FW-MF",
    footed: "Left",
    height: "180cm",
    weight: "77kg",
    birthDate: "July 12, 1991",
    age: 31,
    birthPlace: "Cúcuta, Colombia",
    nationalTeam: "Colombia",
    Club: "Olympiacos",
    img: "James Rodriguez.jpg",
  },
  {
    id: 42,
    name: "Joel Matip",
    position: "DF-MF",
    footed: "Right",
    height: "195cm",
    weight: "89kg ",
    birthDate: "August 8, 1991",
    age: 31,
    birthPlace: "Bochum, Germany",
    nationalTeam: "Germany",
    Club: "Liverpool",
    img: "Joel Matip.jpg",
  },
  {
    id: 43,
    name: "John Stones",
    position: "DF",
    footed: "Right",
    height: "188cm",
    weight: "69kg ",
    birthDate: "May 28, 1994",
    age: 28,
    birthPlace: "Barnsley, England",
    nationalTeam: "England",
    Club: "Manchester City",
    img: "John Stones.jpg",
  },
  {
    id: 44,
    name: "Jordan Henderson",
    position: "MF",
    footed: "Right",
    height: "182cm",
    weight: "67kg",
    birthDate: "June 17, 1990",
    age: 32,
    birthPlace: "Sunderland, England",
    nationalTeam: "England",
    Club: "Liverpool",
    img: "Jordan Henderson.jpg",
  },
  {
    id: 45,
    name: "Jordi Alba",
    position: "DF-MF",
    footed: "Left",
    height: "170cm",
    weight: "68kg ",
    birthDate: "March 21, 1989",
    age: 33,
    birthPlace: "Marmolejo, Spain",
    nationalTeam: "Spain",
    Club: "Barcelona",
    img: "Jordi Alba.jpg",
  },
  {
    id: 46,
    name: "Jorginho",
    position: "MF ",
    footed: "Right",
    height: "180cm",
    weight: "64kg ",
    birthDate: "December 20, 1991",
    age: 31,
    birthPlace: "Imbituba, Brazil",
    nationalTeam: "Italy",
    Club: "Chelsea",
    img: "Jorginho.jpg",
  },
  {
    id: 47,
    name: "Joshua Kimmich",
    position: "DF-MF",
    footed: "Right",
    height: "176cm",
    weight: "69kg ",
    birthDate: "February 8, 1995",
    age: 27,
    birthPlace: "Rottweil, Germany",
    nationalTeam: "Germany",
    Club: "Bayern Munich",
    img: "Joshua Kimmich.jpg",
  },
  {
    id: 48,
    name: "Jules Kounde",
    position: "DF ",
    footed: "Right",
    height: "178cm",
    weight: "69kg ",
    birthDate: "November 12, 1998",
    age: 24,
    birthPlace: "Paris, France",
    nationalTeam: "France",
    Club: "Barcelona",
    img: "Jules Kounde.jpg",
  },
  {
    id: 49,
    name: "Kai Havertz",
    position: "FW-MF",
    footed: "Left",
    height: "186cm",
    weight: "77kg",
    birthDate: "June 11, 1999",
    age: 23,
    birthPlace: "Aachen, Germany",
    nationalTeam: "Germany",
    Club: "Chelsea",
    img: "Kai Havertz.jpg",
  },
  {
    id: 50,
    name: "Kalidou Koulibaly",
    position: "DF",
    footed: "Right",
    height: "195cm",
    weight: "88kg",
    birthDate: "June 20, 1991",
    age: 31,
    birthPlace: "Saint-Dié-des-Vosges, France",
    nationalTeam: "France",
    Club: "Chelsea",
    img: "Kalidou Koulibaly.jpg",
  },
  {
    id: 51,
    name: "Karim Benzema",
    position: "FW",
    footed: "Right",
    height: "183cm",
    weight: "78kg",
    birthDate: "December 19, 1987",
    age: 35,
    birthPlace: "Lyon, France",
    nationalTeam: "France",
    Club: "Real Madrid",
    img: "Karim Benzema.jpg",
  },
  {
    id: 52,
    name: "Kepa Arrizabalaga",
    position: "GK",
    footed: "Right",
    height: "189cm",
    weight: "87kg ",
    birthDate: "October 3, 1994",
    age: 28,
    birthPlace: "Ondarroa, Spain",
    nationalTeam: "Spain",
    Club: "Chelsea",
    img: "Kepa Arrizabalaga.jpg",
  },
  {
    id: 53,
    name: "Kevin De Bruyne",
    position: "FW-MF",
    footed: "Right",
    height: "181cm",
    weight: "69kg ",
    birthDate: "June 28, 1991",
    age: 31,
    birthPlace: "Gent, Belgium",
    nationalTeam: "Belgium",
    Club: "Manchester City",
    img: "Kevin De Bruyne.jpg",
  },
  {
    id: 54,
    name: "Kylian Mbappe",
    position: "FW-MF",
    footed: "Right",
    height: "178cm",
    weight: "73kg ",
    birthDate: "December 20, 1998",
    age: 24,
    birthPlace: "Paris 19 Buttes-Chaumont, France",
    nationalTeam: "France",
    Club: "Paris Saint-Germain",
    img: "Kylian Mbappe.jpg",
  },
  {
    id: 55,
    name: "Luis Diaz",
    position: "FW-MF",
    footed: "Right",
    height: "180cm",
    weight: "72kg ",
    birthDate: "January 13, 1997",
    age: 25,
    birthPlace: "Barrancas, Colombia",
    nationalTeam: "Colombia",
    Club: "Liverpool",
    img: "Luis Diaz.jpg",
  },
  {
    id: 56,
    name: "Luis Suarez",
    position: "FW",
    footed: "Right",
    height: "182cm",
    weight: "84kg ",
    birthDate: "January 24, 1987",
    age: 35,
    birthPlace: "Salto, Uruguay",
    nationalTeam: "Uruguay",
    Club: "Nacional,Barcelona",
    img: "Luis Suarez.jpg",
  },
  {
    id: 57,
    name: "Luka Modric",
    position: "MF",
    footed: "Right",
    height: "174cm",
    weight: "64kg ",
    birthDate: "September 9, 1985",
    age: 37,
    birthPlace: "Zadar, Croatia",
    nationalTeam: "Croatia",
    Club: "Real Madrid",
    img: "Luka Modric.jpg",
  },
  {
    id: 58,
    name: "Andre Ter Stegen",
    position: "GK",
    footed: "Right",
    height: "189cm",
    weight: "84kg",
    birthDate: "April 30, 1992",
    age: 30,
    birthPlace: "Mönchengladbach, Germany",
    nationalTeam: "Germany",
    Club: "Barcelona",
    img: "Marc-Andre Ter Stegen.jpg",
  },
  {
    id: 59,
    name: "Marco Asensio",
    position: "FW-MF",
    footed: "Left",
    height: "178cm",
    weight: "69kg",
    birthDate: "January 21, 1996",
    age: 26,
    birthPlace: "Palma de Mallorca, Spain",
    nationalTeam: "Spain",
    Club: "Real Madrid",
    img: "Marco Asensio.jpg",
  },
  {
    id: 60,
    name: "Marco Reus",
    position: "FW-MF",
    footed: "Right",
    height: "180cm",
    weight: "71kg",
    birthDate: "May 31, 1989",
    age: 33,
    birthPlace: "Kreisfreie Stadt Dortmund, Germany",
    nationalTeam: "Germany",
    Club: "Dortmund",
    img: "Marco Reus.jpg",
  },
  {
    id: 61,
    name: "Marco Verratti",
    position: "MF",
    footed: "Right",
    height: "165cm",
    weight: "59kg ",
    birthDate: "November 5, 1992",
    age: 30,
    birthPlace: "Pescara, Italy",
    nationalTeam: "Italy",
    Club: "Paris Saint-Germain",
    img: "Marco Verratti.jpg",
  },
  {
    id: 62,
    name: "Martin Odegaard",
    position: "FW-MF",
    footed: "Left",
    height: "179cm",
    weight: "68kg",
    birthDate: "December 17, 1998",
    age: 24,
    birthPlace: "Drammen, Norway",
    nationalTeam: "Norway",
    Club: "Arsenal",
    img: "Martin Odegaard.jpg",
  },
  {
    id: 63,
    name: "Mason Mount",
    position: "MF",
    footed: "Right",
    height: "175cm",
    weight: "63kg ",
    birthDate: "January 10, 1999",
    age: 23,
    birthPlace: "Portsmouth, England",
    nationalTeam: "England",
    Club: "Chelsea",
    img: "Mason Mount.jpg",
  },
  {
    id: 64,
    name: "Matthijs de Ligt",
    position: "DF",
    footed: "Right",
    height: "189cm",
    weight: "88kg ",
    birthDate: "August 12, 1999",
    age: 23,
    birthPlace: "Leiderdorp, Netherlands",
    nationalTeam: "Netherlands",
    Club: "Bayern Munich",
    img: "Matthijs de Ligt.jpg",
  },
  {
    id: 65,
    name: "Memphis Depay",
    position: "FW-MF",
    footed: "Right",
    height: "176cm",
    weight: "73kg",
    birthDate: "February 13, 1994",
    age: 28,
    birthPlace: "Moordrecht, Netherlands",
    nationalTeam: "Netherlands",
    Club: "Barcelona",
    img: "Memphis Depay.jpg",
  },
  {
    id: 66,
    name: "Mohamed Salah",
    position: "FW-MF",
    footed: "Left",
    height: "175cm",
    weight: "71kg",
    birthDate: "June 15, 1992",
    age: 30,
    birthPlace: "Basyūn, Egypt",
    nationalTeam: "Egypt",
    Club: "Liverpool",
    img: "Mohamed Salah.jpg",
  },
  {
    id: 67,
    name: "N'Golo Kante",
    position: "MF",
    footed: "Right",
    height: "169cm",
    weight: "68kg",
    birthDate: "March 29, 1991",
    age: 31,
    birthPlace: "Paris, France",
    nationalTeam: "France",
    Club: "Chelsea",
    img: "N Golo Kante.jpg",
  },
  {
    id: 68,
    name: "Naby Keita",
    position: "MF",
    footed: "Right",
    height: "172cm",
    weight: " 71kg",
    birthDate: "February 10, 1995",
    age: 27,
    birthPlace: "Conakry, Guinea",
    nationalTeam: "Guinea",
    Club: "Liverpool",
    img: "Naby Keita.jpg",
  },
  {
    id: 69,
    name: "Neymar Junior",
    position: "FW-MF",
    footed: "Right",
    height: "174cm",
    weight: "68kg",
    birthDate: "February 5, 1992",
    age: 30,
    birthPlace: "Mogi das Cruzes, Brazil",
    nationalTeam: "Brazil",
    Club: "Paris Saint-Germain",
    img: "Neymar.jpg",
  },
  {
    id: 70,
    name: "Ousmane Dembele",
    position: "FW-MF",
    footed: "Both",
    height: "178cm",
    weight: "60kg ",
    birthDate: "May 15, 1997",
    age: 25,
    birthPlace: "Vernon, France",
    nationalTeam: "France",
    Club: "Barcelona",
    img: "Ousmane Dembele.jpg",
  },
  {
    id: 71,
    name: "Pablo Torre",
    position: "MF",
    footed: "Right",
    height: "173cm",
    weight: "63kg ",
    birthDate: "April 3, 2003",
    age: 19,
    birthPlace: "Soto de la Marina, Spain",
    nationalTeam: "Spain",
    Club: "Barcelona",
    img: "Pablo Torre.jpg",
  },
  {
    id: 72,
    name: "Paul Pogba",
    position: "MF",
    footed: "Right",
    height: "191cm",
    weight: "83kg ",
    birthDate: "",
    age: 29,
    birthPlace: "Lagny-sur-Marne, France",
    nationalTeam: "France",
    Club: "Juventus",
    img: "Paul Pogba.jpg",
  },
  {
    id: 73,
    name: "Paulo Dybala",
    position: "FW-MF",
    footed: "Left",
    height: "175cm",
    weight: "73kg ",
    birthDate: "November 15, 1993",
    age: 29,
    birthPlace: "Laguna Larga, Argentina",
    nationalTeam: "Argentina",
    Club: "Roma",
    img: "Paulo Dybala.jpg",
  },
  {
    id: 74,
    name: "Pedri Gonzalez",
    position: "MF",
    footed: "Right",
    height: "174cm",
    weight: "63kg",
    birthDate: "November 25, 2002",
    age: 20,
    birthPlace: "Bajamar, Spain",
    nationalTeam: "Spain",
    Club: "Barcelona",
    img: "Pedri.jpg",
  },
  {
    id: 75,
    name: "Pep Guardiola",
    position: "Coach",
    footed: "unKnown",
    height: "180cm",
    weight: "77kg",
    birthDate: "January 18, 1971",
    age: 52,
    birthPlace: "Santpedor, Spain",
    nationalTeam: "Spain",
    Club: "Manchester City Coach",
    img: "Pep Guardiola.jpg",
  },
  {
    id: 76,
    name: "Phil Foden",
    position: "FW-MF",
    footed: "Left",
    height: "169cm",
    weight: "69kg",
    birthDate: "May 28, 2000",
    age: 22,
    birthPlace: "Stockport, England",
    nationalTeam: "England",
    Club: "Manchester City",
    img: "Phil Foden.jpg",
  },
  {
    id: 77,
    name: "Raheem Sterling",
    position: "FW-MF",
    footed: "Right",
    height: "170cm",
    weight: "69kg",
    birthDate: "December 8, 1994",
    age: 28,
    birthPlace: "Kingston, Jamaica",
    nationalTeam: "England",
    Club: "Chelsea",
    img: "Raheem Sterling.jpg",
  },
  {
    id: 78,
    name: "Raphael Varane",
    position: "DF-MF",
    footed: "Both",
    height: "194cm",
    weight: "83kg",
    birthDate: "April 25, 1993",
    age: 29,
    birthPlace: "Lille, France",
    nationalTeam: "France",
    Club: "Manchester United",
    img: "Raphael Varane.jpg",
  },
  {
    id: 79,
    name: "Raphinha",
    position: "FW-MF",
    footed: "Left",
    height: "176cm",
    weight: "78kg",
    birthDate: "December 14, 1996",
    age: 26,
    birthPlace: "Porto Alegre, Brazil",
    nationalTeam: "Brazil",
    Club: "Barcelona",
    img: "Raphinha.jpg",
  },
  {
    id: 80,
    name: "Reece James",
    position: "DF-MF",
    footed: "Right",
    height: "172cm",
    weight: "63kg",
    birthDate: "December 8, 1999",
    age: 23,
    birthPlace: "London, England",
    nationalTeam: "England",
    Club: "Chelsea",
    img: "Reece James.jpg",
  },
  {
    id: 81,
    name: "Robert Lewandowski",
    position: "FW",
    footed: "Right",
    height: "185cm",
    weight: "78kg",
    birthDate: "August 21, 1988",
    age: 34,
    birthPlace: "Warsaw, Poland",
    nationalTeam: "Poland",
    Club: "Barcelona",
    img: "Robert Lewandowski.jpg",
  },
  {
    id: 82,
    name: "Roberto Firmino",
    position: "FW-MF",
    footed: "Right",
    height: "181cm",
    weight: "76kg",
    birthDate: "October 2, 1991",
    age: 31,
    birthPlace: "Maceió, Brazil",
    nationalTeam: "Brazil",
    Club: "Liverpool",
    img: "Roberto Firmino.jpg",
  },
  {
    id: 83,
    name: "Rodrigo Hernandez",
    position: "MF",
    footed: "Right",
    height: "190cm",
    weight: "78kg",
    birthDate: "June 22, 1996",
    age: 26,
    birthPlace: "Madrid, Spain",
    nationalTeam: "Spain",
    Club: "Manchester City",
    img: "Rodrigo Hernandez.jpg",
  },
  {
    id: 84,
    name: "Rodrygo Goes",
    position: "FW-MF",
    footed: "Right",
    height: "174cm",
    weight: " 68kg",
    birthDate: "January 9, 2001",
    age: 21,
    birthPlace: "Osasco, Brazil",
    nationalTeam: "Brazil",
    Club: "Real Madrid",
    img: "Rodrygo Goes.jpg",
  },
  {
    id: 85,
    name: "Sadio Mane",
    position: "FW-MF",
    footed: "Right",
    height: "175cm",
    weight: "68kg",
    birthDate: "April 10, 1992",
    age: 30,
    birthPlace: "Sédhiou, Senegal",
    nationalTeam: "Senegal",
    Club: "Bayern Munich",
    img: "Sadio Mane.jpg",
  },
  {
    id: 86,
    name: "Sergio Ramos",
    position: "DF",
    footed: "Right",
    height: "183cm",
    weight: "74kg",
    birthDate: "March 30, 1986",
    age: 36,
    birthPlace: "Camas, Spain",
    nationalTeam: "Spain",
    Club: "Paris Saint-Germain",
    img: "Sergio Ramos.jpg",
  },
  {
    id: 87,
    name: "Thiago Alcantara",
    position: "MF",
    footed: "Right",
    height: "172cm",
    weight: "59kg",
    birthDate: "April 11, 1991",
    age: 31,
    birthPlace: "San Pietro Vernotico, Italy",
    nationalTeam: "Spain",
    Club: "Liverpool",
    img: "Thiago Alcantara.jpg",
  },
  {
    id: 88,
    name: "Thibaut Courtois",
    position: "GK",
    footed: "Left",
    height: "199cm",
    weight: "91kg",
    birthDate: "May 11, 1992",
    age: 30,
    birthPlace: "Bree, Belgium",
    nationalTeam: "Belgium",
    Club: "Real Madrid",
    img: "Thibaut Courtois.jpg",
  },
  {
    id: 89,
    name: "Timo Werner",
    position: "FW-MF",
    footed: "Right",
    height: "180cm",
    weight: "74kg",
    birthDate: "March 6, 1996",
    age: 26,
    birthPlace: "Stuttgart, Germany",
    nationalTeam: "Germany",
    Club: "RB Leipzig",
    img: "Timo Werner.jpg",
  },
  {
    id: 90,
    name: "Toni Kroos",
    position: "MF",
    footed: "Right",
    height: "182cm",
    weight: "78kg",
    birthDate: "January 4, 1990",
    age: 33,
    birthPlace: "Greifswald, Germany",
    nationalTeam: "Germany",
    Club: "Real Madrid",
    img: "Toni Kroos.jpg",
  },
  {
    id: 91,
    name: "Alexander Arnold",
    position: "DF",
    footed: "Right",
    height: "175cm",
    weight: "68kg",
    birthDate: "October 7, 1998",
    age: 24,
    birthPlace: "Liverpool, England",
    nationalTeam: "England",
    Club: "Liverpool",
    img: "Alexander Arnold.jpg",
  },
  {
    id: 92,
    name: "Vinicius Junior",
    position: "FW-MF",
    footed: "Right",
    height: "177cm",
    weight: "62kg",
    birthDate: "July 12, 2000",
    age: 22,
    birthPlace: "São Gonçalo, Brazil",
    nationalTeam: "Brazil",
    Club: "Real Madrid",
    img: "Vinicius Junior.jpg",
  },
  {
    id: 93,
    name: "Virgil van Dijk",
    position: "DF (CB, left)",
    footed: "Right",
    height: "193cm",
    weight: "87kg",
    birthDate: "July 8, 1991",
    age: 31,
    birthPlace: "Breda, Netherlands",
    nationalTeam: "Netherlands",
    Club: "Liverpool",
    img: "Virgil van Dijk.jpg",
  },
  {
    id: 94,
    name: "Ferland Mendy",
    position: "DF",
    footed: "Left",
    height: "178cm",
    weight: "73kg",
    birthDate: "June 8, 1995",
    age: 27,
    birthPlace: "Meulan-en-Yvelines, France",
    nationalTeam: "France",
    Club: "Real Madrid",
    img: "Ferland Mendy.jpg",
  },
  {
    id: 95,
    name: "Alisson Becker",
    position: "GK",
    footed: "Right",
    height: "193cm",
    weight: "91kg",
    birthDate: "October 2, 1992",
    age: 30,
    birthPlace: "Novo Hamburgo, Brazil",
    nationalTeam: "Brazil",
    Club: "Liverpool",
    img: "Alisson Becker.jpg",
  },
  {
    id: 96,
    name: "Joao Felix",
    position: "FW-MF",
    footed: "Right",
    height: "180cm",
    weight: "63kg",
    birthDate: "November 10, 1999",
    age: 23,
    birthPlace: "Viseu, Portugal",
    nationalTeam: "Portugal",
    Club: "Atletico Madrid",
    img: "Joao Felix.jpg",
  },
  {
    id: 97,
    name: "Antoine Griezmann",
    position: "FW-MF",
    footed: "Left",
    height: "175cm",
    weight: "67kg",
    birthDate: "March 21, 1991",
    age: 31,
    birthPlace: "Mâcon, France",
    nationalTeam: "France",
    Club: "Atletico Madrid",
    img: "Antoine Griezmann.jpg",
  },
  {
    id: 98,
    name: "Jan Oblak",
    position: "GK",
    footed: "Right",
    height: "186cm",
    weight: "87kg",
    birthDate: "January 7, 1993",
    age: 30,
    birthPlace: "Škofja Loka, Slovenia",
    nationalTeam: "Slovenia",
    Club: "Atletico Madrid",
    img: "Jan Oblak.jpg",
  },
];

export default playersData;
