let DefaultPlayers = [
  {
    id: 1,
    name: "Lionel Messi",
    position: "FW-MF",
    age: 35,
    birthDate: "June 24, 1987",
    birthPlace: "Rosario, Argentina",
    height: "170cm",
    weight: "72kg",
    footed: "Left",
    nationalTeam: "Argentina",
    Club: "Paris Saint-Germain",
    img: "Lionel Messi.jpg",
  },
  {
    id: 2,
    name: "Cristiano Ronaldo",
    position: "FW-MF",
    age: 37,
    birthDate: "February 5, 1985",
    birthPlace: "Funchal, Portugal",
    height: "187cm",
    weight: "83kg ",
    footed: "Right",
    nationalTeam: " Portugal",
    Club: "Al Nasr (KSA)",
    img: "Cristiano Ronaldo.jpg",
  },
  {
    id: 69,
    name: "Neymar Junior",
    position: "FW-MF",
    footed: "Right",
    height: "174cm",
    weight: "68kg",
    birthDate: "February 5, 1992",
    age: 30,
    birthPlace: "Mogi das Cruzes, Brazil",
    nationalTeam: "Brazil",
    Club: "Paris Saint-Germain",
    img: "Neymar.jpg",
  },
  {
    id: 54,
    name: "Kylian Mbappe",
    position: "FW-MF",
    footed: "Right",
    height: "178cm",
    weight: "73kg ",
    birthDate: "December 20, 1998",
    age: 24,
    birthPlace: "Paris 19 Buttes-Chaumont, France",
    nationalTeam: "France",
    Club: "Paris Saint-Germain",
    img: "Kylian Mbappe.jpg",
  },
  {
    id: 25,
    name: "Erling Haaland",
    position: "FW ",
    footed: "Left",
    height: "191cm",
    weight: "87kg ",
    birthDate: "July 21, 2000",
    age: 22,
    birthPlace: "Leeds, England",
    nationalTeam: "Norway",
    Club: "Manchester City",
    img: "Erling Haaland.jpg",
  },
  {
    id: 81,
    name: "Robert Lewandowski",
    position: "FW",
    footed: "Right",
    height: "185cm",
    weight: "78kg",
    birthDate: "August 21, 1988",
    age: 34,
    birthPlace: "Warsaw, Poland",
    nationalTeam: "Poland",
    Club: "Barcelona",
    img: "Robert Lewandowski.jpg",
  },
  {
    id: 66,
    name: "Mohamed Salah",
    position: "FW-MF",
    footed: "Left",
    height: "175cm",
    weight: "71kg",
    birthDate: "June 15, 1992",
    age: 30,
    birthPlace: "Basyūn, Egypt",
    nationalTeam: "Egypt",
    Club: "Liverpool",
    img: "Mohamed Salah.jpg",
  },
  {
    id: 97,
    name: "Antoine Griezmann",
    position: "FW-MF",
    footed: "Left",
    height: "175cm",
    weight: "67kg",
    birthDate: "March 21, 1991",
    age: 31,
    birthPlace: "Mâcon, France",
    nationalTeam: "France",
    Club: "Atletico Madrid",
    img: "Antoine Griezmann.jpg",
  },
  {
    id: 51,
    name: "Karim Benzema",
    position: "FW",
    footed: "Right",
    height: "183cm",
    weight: "78kg",
    birthDate: "December 19, 1987",
    age: 35,
    birthPlace: "Lyon, France",
    nationalTeam: "France",
    Club: "Real Madrid",
    img: "Karim Benzema.jpg",
  },
  {
    id: 4,
    name: "Bernardo Silva",
    position: "FW-MF",
    age: 28,
    birthDate: "August 10, 1994",
    birthPlace: "Lisbon, Portugal",
    height: "173cm",
    weight: "64kg",
    footed: "Left",
    nationalTeam: "Portugal",
    Club: "Manchester City",
    img: "Bernardo Silva.jpg",
  },
  {
    id: 5,
    name: "Angel Di Maria",
    position: "FW-MF",
    age: 34,
    birthDate: "February 14, 1988",
    birthPlace: "Rosario, Argentina",
    height: "180cm",
    weight: "69kg ",
    footed: "Left",
    nationalTeam: "Argentina",
    Club: "Juventus",
    img: "Angel Di Maria.jpg",
  },
  {
    id: 53,
    name: "Kevin De Bruyne",
    position: "FW-MF",
    footed: "Right",
    height: "181cm",
    weight: "69kg ",
    birthDate: "June 28, 1991",
    age: 31,
    birthPlace: "Gent, Belgium",
    nationalTeam: "Belgium",
    Club: "Manchester City",
    img: "Kevin De Bruyne.jpg",
  },
  {
    id: 96,
    name: "Joao Felix",
    position: "FW-MF",
    footed: "Right",
    height: "180cm",
    weight: "63kg",
    birthDate: "November 10, 1999",
    age: 23,
    birthPlace: "Viseu, Portugal",
    nationalTeam: "Portugal",
    Club: "Atletico Madrid",
    img: "Joao Felix.jpg",
  },
  {
    id: 57,
    name: "Luka Modric",
    position: "MF",
    footed: "Right",
    height: "174cm",
    weight: "64kg ",
    birthDate: "September 9, 1985",
    age: 37,
    birthPlace: "Zadar, Croatia",
    nationalTeam: "Croatia",
    Club: "Real Madrid",
    img: "Luka Modric.jpg",
  },
  {
    id: 74,
    name: "Pedri Gonzalez",
    position: "MF",
    footed: "Right",
    height: "174cm",
    weight: "63kg",
    birthDate: "November 25, 2002",
    age: 20,
    birthPlace: "Bajamar, Spain",
    nationalTeam: "Spain",
    Club: "Barcelona",
    img: "Pedri.jpg",
  },
  {
    id: 37,
    name: "Harry Kane",
    position: "FW ",
    footed: "Right",
    height: "188cm",
    weight: "73kg",
    birthDate: "July 28, 1993",
    age: 29,
    birthPlace: "Walthamstow, England",
    nationalTeam: "England",
    Club: "Tottenham Hotspur",
    img: "Harry Kane.jpg",
  },
  {
    id: 32,
    name: "Gabriel Jesus",
    position: "FW-MF",
    footed: "Right",
    height: "177cm",
    weight: "72kg",
    birthDate: "April 3, 1997",
    age: 25,
    birthPlace: "São Paulo, Brazil",
    nationalTeam: "Brazil",
    Club: "Arsenal",
    img: "Gabriel Jesus.jpg",
  },
  {
    id: 3,
    name: "Ansu Fati",
    position: "FW",
    age: 20,
    birthDate: "October 31, 2002",
    birthPlace: "Bissau, Guinea-Bissau",
    height: "178cm",
    weight: "68kg",
    footed: "Right",
    nationalTeam: "Spain",
    Club: "Barcelona",
    img: "Ansu Fati.jpg",
  },
  {
    id: 58,
    name: "Andre Ter Stegen",
    position: "GK",
    footed: "Right",
    height: "189cm",
    weight: "84kg",
    birthDate: "April 30, 1992",
    age: 30,
    birthPlace: "Mönchengladbach, Germany",
    nationalTeam: "Germany",
    Club: "Barcelona",
    img: "Marc-Andre Ter Stegen.jpg",
  },
  {
    id: 88,
    name: "Thibaut Courtois",
    position: "GK",
    footed: "Left",
    height: "199cm",
    weight: "91kg",
    birthDate: "May 11, 1992",
    age: 30,
    birthPlace: "Bree, Belgium",
    nationalTeam: "Belgium",
    Club: "Real Madrid",
    img: "Thibaut Courtois.jpg",
  },
  {
    id: 95,
    name: "Alisson Becker",
    position: "GK",
    footed: "Right",
    height: "193cm",
    weight: "91kg",
    birthDate: "October 2, 1992",
    age: 30,
    birthPlace: "Novo Hamburgo, Brazil",
    nationalTeam: "Brazil",
    Club: "Liverpool",
    img: "Alisson Becker.jpg",
  },
];
export default DefaultPlayers;
